import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReduxProvider } from "../store/ReduxProvider";
import FetchInterceptor from "@/app/response-interceptor";
import "./globals.css";

const PeydaRegular = localFont({
  src: "../public/fonts/PeydaFaNum-Regular.ttf",
  // variable: "--font-geist-sans",
  // weight: "100 900",
});

export const metadata: Metadata = {
  title: "پنل فروشگاه",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PeydaRegular.className}>
        <ReduxProvider>
          <FetchInterceptor />
          {children}
          <div id="modal" />
        </ReduxProvider>
      </body>
    </html>
  );
}
